// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5cnTs6gTfmxOhY50O03_OikzNap27gcQ',
    appId: '1:658908988315:android:fe65a555b03cc3cc6b973e',
    messagingSenderId: '658908988315',
    projectId: 'autoaid-dev',
    databaseURL: 'https://autoaid-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoaid-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0Hem0imSC0-wmG75IHAmeETv9exBpuU',
    appId: '1:658908988315:ios:046ff129720c63716b973e',
    messagingSenderId: '658908988315',
    projectId: 'autoaid-dev',
    databaseURL: 'https://autoaid-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoaid-dev.firebasestorage.app',
    iosBundleId: 'com.example.autoaidFinalProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ROhZjn0Wb5NMkFTnZQslfXBMqBn8luw',
    appId: '1:658908988315:web:d2873298c2aa3b576b973e',
    messagingSenderId: '658908988315',
    projectId: 'autoaid-dev',
    authDomain: 'autoaid-dev.firebaseapp.com',
    databaseURL: 'https://autoaid-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoaid-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0Hem0imSC0-wmG75IHAmeETv9exBpuU',
    appId: '1:658908988315:ios:046ff129720c63716b973e',
    messagingSenderId: '658908988315',
    projectId: 'autoaid-dev',
    databaseURL: 'https://autoaid-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoaid-dev.firebasestorage.app',
    iosBundleId: 'com.example.autoaidFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ROhZjn0Wb5NMkFTnZQslfXBMqBn8luw',
    appId: '1:658908988315:web:a8ee9b2a3bfcfdc46b973e',
    messagingSenderId: '658908988315',
    projectId: 'autoaid-dev',
    authDomain: 'autoaid-dev.firebaseapp.com',
    databaseURL: 'https://autoaid-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'autoaid-dev.firebasestorage.app',
  );

}